title: <p align="center"> K G</p>
#logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/kishore-george/">LinkedIn</a> |
  <a href="https://github.com/kishore-n-george">GitHub</a>
  
  <br>   
    Test jekyll
  <br>
  </p>

theme: jekyll-theme-minimal
